config/routes.rb
QPT2a::Application.routes.draw do

  root :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/imprint', :to => 'pages#imprint'
  
  get 'logout' => 'sessions#destroy', :as => 'log_out'
  get 'login' => 'sessions#new', :as => 'log_in'
  get 'signup' => 'users#new', :as => 'sign_up'
  
  resources :projects do
    # root :to => "users#show"
	
	get :work, :on => :collection
    get :study, :on => :collection
	
	resources :to_dos

    member do
	  get "todos"
	  get "time"
	end
  end

  resources :to_dos do
    get :done, :on => :collection
    get :outstanding, :on => :collection
  end

  resources :users do 
    resources :projects
  end 

  resources :sessions do
  
  end

end

app/models/project.rb
class Project < ActiveRecord::Base

  validates :title, :kind, presence: true

  belongs_to :user
  has_many :to_dos, :dependent => :destroy
  
  validates :user_id, :presence => true
  
  def self.work
    where("kind = ?", "work")
  end
  
  def self.study
    where("kind = ?", "study")
  end
  
  def self.todos
    
  end
	
	
end

app/models/to_do.rb
class ToDo < ActiveRecord::Base

  validates :title, :deadline, presence: true
  
  belongs_to :project
  
  default_scope :order => 'to_dos.deadline ASC'

  def self.outstanding
    where("done = ?", false)
  end
  
  def self.done
    where("done = ?", true)
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :projects, :dependent => :destroy
  
  attr_accessible :first_name, :last_name, :user_name, :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :user_name
  validates_uniqueness_of :user_name
  validates_presence_of :first_name
  validates_presence_of :email

  def self.authenticate(user_name, password)
    user = find_by_user_name(user_name)

    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  public
  
  # rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  # private

  # def record_not_found
	# render :template => "404.html.erb", :status => 404
  # end
  
  def rescue_action_in_public(exception)
  set_meta("robots","noindex")
  case exception
     when ::ActiveRecord::RecordNotFound
     when ::ActiveRecord::RecordInvalid
     when ::ActionController::RoutingError
     when ::ActionController::UnknownController
     when ::ActionController::UnknownAction
     when ::ActionController::MethodNotAllowed
       render :template => "404.html.erb", :status => 404
     else
       render :template => "500.html.erb", :status => 500
   end
end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def about
    @title = "About"
  end

  def imprint
    @title = "Impressum"
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = current_user.projects.includes(:to_dos).where(['to_dos.done = ?', false]).order('to_dos.deadline ASC').limit(6)

	@title = "Dashboard"
  end
  
  def work
    @projects = current_user.projects.work
	
	@title = "Projekte"
  end
  
  def study
    @projects = current_user.projects.study
	
	@title = "Lehrveranstaltungen"
  end
	
  def show
    @project = Project.find(params[:id])

	@to_dos = @project.to_dos.limit(10)
	@worklist = current_user.projects.work.order('projects.title ASC').limit(20)
	@studylist = current_user.projects.study.order('projects.title ASC').limit(20)
	
	@title = @project.title
  end
  
  def todos
    @project = current_user.projects.find(params[:id])
	@to_dos = @project.to_dos

	@worklist = current_user.projects.work.order('projects.title ASC').limit(20)
	@studylist = current_user.projects.study.order('projects.title ASC').limit(20)

	@title = @project.title
  end
  
  def time 
    @project = current_user.projects.find(params[:id])
	@to_dos = @project.to_dos
	
	@worklist = current_user.projects.work.order('projects.title ASC').limit(20)
	@studylist = current_user.projects.study.order('projects.title ASC').limit(20)
    
	@title = @project.title
  end 

  def new
    @project = current_user.projects.new
  end

  def edit
    @project = current_user.projects.find(params[:id])
  end

  def create
    @project = Project.new(params[:project])
	
    if @project.save
      redirect_to @project
    else
      render "new"
    end
  end

  def update
    @project = current_user.projects.find(params[:id])

    if @project.update_attributes(params[:project])
      redirect_to @project
    else
      render "edit"
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to projects_url
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
	end

	def create
		user = User.authenticate(params[:user_name], params[:password])
		if user
			session[:user_id] = user.id
			redirect_to projects_path, :notice => "Logged in!"
		else
			flash.now.alert = "Invalid user_name or password"
			render "new"
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url, :notice => "Logged out!"
	end
end

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController

  def index
    @to_dos = ToDo.all
  end
  
  def done
    @to_dos = ToDo.done
  end
  
  def outstanding
    @to_dos = ToDo.outstanding
  end

  def show
    @project = Project.find(params[:project_id])
    @to_do = @project.to_dos.find(params[:id])
	
	@todolist = @project.to_dos.outstanding.order('to_dos.deadline ASC').limit(20)
	
	@title = @project.title
  end

  def new
    @project = Project.find(params[:project_id])
    @to_do = ToDo.new
	@title = "Neue Aufgabe erstellen"
  end

  def edit
    @project = Project.find(params[:project_id])
    @to_do = @project.to_dos.find(params[:id])
	@title = "Aufgabe bearbeiten"
  end
  
  def create
    @project = Project.find(params[:project_id])
	@to_do = @project.to_dos.new(params[:to_do])

    if @to_do.save
      redirect_to [@project, @to_do]
    else
       render action: 'new'
    end
  end

  def update
    @project = Project.find(params[:project_id])
    @to_do = @project.to_dos.find(params[:id])

    if @to_do.update_attributes(params[:to_do])
      redirect_to [@project, @to_do]
    else
      render action: 'edit'
    end
  end

  def destroy
    @to_do = ToDo.find(params[:id])
    @to_do.destroy

    redirect_to projects_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
	@title = @user.user_name
	
	@projects = @user.projects
	@worklist = @projects.work.order('projects.title ASC').limit(20)
	@studylist = @projects.study.order('projects.title ASC').limit(20)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to new_session_path, :notice => "Signed up!"
    else
      render "new"
    end
  end

	def edit
    @user = User.find(params[:id])
  end
	
	def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
	
end

app/helpers/application_helper.rb
module ApplicationHelper

  def controller_stylesheet
    controller_name = controller.controller_name
    if File.exists?( "#{Rails.root}/app/assets/stylesheets/#{controller_name}.css" )
      stylesheet_link_tag( controller_name )
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/to_dos_helper.rb
module ToDosHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { :size => 57 })
    gravatar_image_tag(user.email.downcase, :alt => h(user.user_name),
                                            :class => 'gravatar',
                                            :gravatar => options)
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>GetItDone | <%= @title %></title>
<meta name="description" content="" />
<meta name="keywords" content="" />

<%= stylesheet_link_tag "reset", :media => "screen" %>
<%= stylesheet_link_tag "style", :media => "screen" %>
<%= controller_stylesheet %>
<% if content_for?(:stylesheet) %>
<%= yield :stylesheet %>
<% end %>

<%= javascript_include_tag "script" %>

<%= csrf_meta_tags %>
</head>
<body>

<div id="wrap">
  <header id="header-wrap">
    <hgroup id="header">
      <h3 id="logo"><a href="">GetItDone</a></h3>
	  <% if current_user %>
	  <div id="avatar">
	    <%= gravatar_for current_user %>
	  </div>
	  <% end %>
	  <ul id="header-menu">
	  <% if current_user %>
        <li>Hallo <%= current_user.first_name %>!</li>
		<li><%= link_to 'Dashboard', projects_path %></li>
		<li><%= link_to 'Profil', user_path(current_user) %></li>
        <li><%= link_to 'Log out', log_out_path %></li>
      <% else %>
	    <li><%= link_to 'Home', root_path %></li>
		<li><%= link_to 'About', about_path %></li>
        <li><%= link_to "Login", log_in_path %>/<%= link_to "Register", sign_up_path %></li>
      <% end %>
	  </ul>
	  <% if content_for?(:headertitle) %>
	    <h1 id="header-title"><%= yield :headertitle %></h1>
	  <% end %>
    </hgroup>
  </header>

  <section id="content-wrap">
    <% if content_for?(:contentmenu) %>
      <ul id="content-menu-top">
	    <%= yield :contentmenu %>
      </ul>
    <% end %>
    <div id="content" class="<%= content_for?(:sidebar) ? 'narrow' : 'wide' %>">
      <%= yield %>
    </div>
	<% if content_for?(:sidebar) %>
      <div id="sidebar">
	    <aside class="actions">
	      <%= link_to 'Dashboard', projects_path, :class => 'dashboard' %>
	    <%= yield :sidebar %>
      </div>
    <% end %>
  </section>

  <footer id="footer">
    <p>&copy; by Nicole Buchegger &amp; Barbara Huber | FH Salzburg 2011 <span><a href="mailto:support@getitdone.com">support@getitdone.com</a> <%= link_to "Impressum", imprint_path %></span></p>
  </footer>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<div id="infobox-1" class="infobox">
  <h3>Infobox 1</h3>
</div>
<div id="infobox-2" class="infobox">
  <h3>Infobox 2</h3>
</div>
<div id="infobox-3" class="infobox">
  <h3>Infobox 3</h3>
</div>

<div id="more-info">
  <p>Mehr Informationen über GetItDone steht hier. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
</div>

app/views/pages/imprint.html.erb
<h1>Pages#imprint</h1>
<p>Find me in app/views/pages/imprint.html.erb</p>

app/views/projects/_form.html.erb
<%= form_for([@user, @project]) do |f| %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description, :maxlength => 140 %>
  </p>
  <p>
    <%= f.radio_button :kind, 'work' %> <label>Arbeit - Projekt</label><br />
	<%= f.radio_button :kind, 'study' %> <label>Studium - LVA</label>
  </p>
  <%= f.hidden_field :user_id %>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/projects/_projectlist.html.erb
<aside>
<h4>Aktuelle Projekte:</h4>
<ul class="worklist">
<% @worklist.each do |work| %>
    <li><%= link_to work.title, work %></li>
<% end %>
</ul>
<h4>Aktuelle Lehrveranstaltungen:</h4>
<ul class="studylist">
<% @studylist.each do |study| %>
    <li><%= link_to study.title, study %></li>
<% end %>
</ul>
</aside>

app/views/projects/edit.html.erb
<h2 class="site-title">Projekt bearbeiten</h2>
<h4 class="site-subtitle"><%= @project.title %></h4>

<%= render 'form' %>


<% content_for :headertitle do %>
   <%= @project.title %>
<% end %>

<% content_for :contentmenu do %>
   <li><%= link_to "Übersicht", project_path %></li>
   <li><%= link_to "Aufgaben", todos_project_path %></li>
   <li><%= link_to "Zeit", time_project_path %></li>
<% end %>

app/views/projects/index.html.erb
<p class="actions">&raquo; <%= link_to 'neues Projekt / neue LVA erstellen', new_project_path, :class => "create-new" %></p>

<div class="recent-projects">
<% @projects.each do |project| %>
  <div id="project-<%= project.id %>" class="project <%= project.kind %>">
    <h4>
	  <%= link_to project.title, project %>
	  <div class="project-actions">
        <%= link_to 'Projekt löschen', project, confirm: 'Are you sure?', method: :delete, :class => "delete" %>
        <%= link_to 'Projekt bearbeiten', edit_project_path(project), :class => "edit" %>
      </div>
	</h4>
    <div>
	  <ul>
      <% project.to_dos.outstanding.limit(5).each do |to_do| %>
        <li><a href="/projects/<%= project.id %>/to_dos/<%= to_do.id %>"><%= to_do.title %></a></li>
      <% end %>
      </ul>
      <p>Zeiterfassung gesamt: <strong><%= project.to_dos.sum(:time) %> Stunden</strong></p>
    </div>		
  </div>
<% end %>
</div>

<% content_for :contentmenu do %>
   <li><%= link_to 'Dashboard', projects_path, :class => "active" %></li>
   <li><%= link_to 'Arbeit', work_projects_path %></li>
   <li><%= link_to 'Studium', study_projects_path %></li>
<% end %>

app/views/projects/show.html.erb
<p class="project-description"><%= @project.description %></p>

<% unless @project.to_dos.empty? %>
<h3 class="project-todo">Aufgaben (<%= @project.to_dos.outstanding.count %>):</h3>
  <ul class="project-todos">
  <% @project.to_dos.outstanding.each do |to_do| %>
    <li>
	  <a href="/projects/<%= @project.id %>/to_dos/<%= to_do.id %>"><%= to_do.title %></a>
	  <!-- <%= link_to to_do.title, project_to_do_path(@project) %> -->
	</li>
  <% end %>
  </ul>
<% end %>

<p class="actions bottom">&raquo; <%= link_to 'zurück zum Dashboard', projects_path, :class => "back-to-dashboard" %></p>


<% content_for :headertitle do %>
   <%= @project.title %>
<% end %>

<% content_for :contentmenu do %>
   <li><%= link_to "Übersicht", project_path, :class => "active" %></li>
   <li><%= link_to "Aufgaben", todos_project_path %></li>
   <li><%= link_to "Zeit", time_project_path %></li>
<% end %>

<% content_for :sidebar do %>
	<%= link_to 'Projekt / LVA löschen', @project, confirm: 'Bist du sicher, dass du dieses Projekt/diese LVA löschen möchtest?', method: :delete, :class => 'project-delete', :title => 'Projekt/LVA löschen' %>
    <%= link_to 'Projekt / LVA bearbeiten', edit_project_path(@project), :class => 'project-edit', :title => 'Projekt/LVA bearbeiten' %>
  </aside>
  <%= render 'projectlist' %>
<% end %>

app/views/projects/study.html.erb
<p class="actions">&raquo; <%= link_to 'neue LVA erstellen', new_project_path, :class => "create-new" %></p>

<ul class="overview overview-study">
<% @projects.each do |project| %>
  <li id="project-<%= project.id %>">
    <h4>
	  <%= link_to project.title, project %>
	  <div class="project-actions">
	    <%= link_to 'Show', project %>
        <%= link_to 'Edit', edit_project_path(project) %>
        <%= link_to 'Destroy', project, confirm: 'Are you sure?', method: :delete %>
      </div>
	</h4>
	<p><%= project.description %></p>

    <p class="time">Zeiterfassung gesamt: <strong><%= project.to_dos.sum(:time) %> Stunden</strong></p>	
  </li>
<% end %>
</ul>


<% content_for :contentmenu do %>
   <li><%= link_to "Dashboard", projects_path %></li>
   <li><%= link_to "Arbeit", work_projects_path %></li>
   <li><%= link_to "Studium", study_projects_path, :class => "active" %></li>
<% end %>

app/views/projects/time.html.erb
<h2 class="site-title">Zeiterfassung</h2>
<h4 class="site-subtitle"><%= @project.title %></h4>

<% if @project.to_dos.done.empty? %>
  <p class="info">Es sind noch keine Aufgaben dieses Projektes abgeschlossen. Kennzeichne fertige Aufgaben als "erledigt".</p>
<% else %>
  <ul class="todos">
  <% @project.to_dos.done.each do |to_do| %>
    <li>
	  Erledigt am: <%= to_do.updated_at.to_formatted_s(:time_format) %><br />
	  Titel: <a href="/projects/<%= @project.id %>/to_dos/<%= to_do.id %>"><%= to_do.title %></a><br />
	  Aufgewendete Zeit: <%= to_do.time %> Stunden
	</li>
  <% end %>
  </ul>
<% end %>

<p class="actions bottom">&raquo; <%= link_to 'zurück zum Dashboard', projects_path, :class => "back-to-dashboard" %></p>
<p> </p>

<% content_for :headertitle do %>
   <%= @project.title %>
<% end %>

<% content_for :contentmenu do %>
   <li><%= link_to "Übersicht", project_path%></li>
   <li><%= link_to "Aufgaben", todos_project_path %></li>
   <li><%= link_to "Zeit", time_project_path, :class => "active" %></li>
<% end %>

<% content_for :sidebar do %>
    <%= link_to 'Neue Aufgabe hinzufügen', new_project_to_do_path(@project), :class => 'todo-add', :title => 'Neue Aufgabe hinzufügen' %>
  </aside>
  <%= render 'projectlist' %>
<% end %>

app/views/projects/todos.html.erb
<h2 class="site-title"><%= @project.to_dos.outstanding.count %> Aufgaben</h2>
<h4 class="site-subtitle"><%= @project.title %></h4>

<% if @project.to_dos.outstanding.empty? %>
  <p class="info">Entweder es sind alle Aufgaben dieses Projektes/dieser Lehrveranstaltung erledigt oder es wurden noch keine Aufgaben für dieses Projekt/diese Lehrveranstaltung hinzugefügt!</p>
  <p class="info">Du kannst eine <%= link_to 'neue Aufgabe hinzufügen', new_project_to_do_path(@project) %> oder dich entspannt zurücklehnen...</p>
<% else %>
  <ul class="todos">
  <% @project.to_dos.outstanding.each do |to_do| %>
    <li>
	  <a href="/projects/<%= @project.id %>/to_dos/<%= to_do.id %>"><%= to_do.title %></a><br />
	  <%= to_do.short_description %> <span>Deadline: <%= to_do.deadline.to_formatted_s(:date_format) %></span>
	</li>
  <% end %>
  </ul>
<% end %>

<h5>Erledigte Aufgaben:</h5>
<% if @project.to_dos.done.empty? %>
  <p class="info">Es gibt noch keine erledigten Aufgaben!</p>
<% else %>
<ul class="done">
  <% @project.to_dos.done.each do |done_to_do| %>
  <li><strike><%= done_to_do.title %></strike></li>
  <% end %>
</ul>
<% end %>

<p class="actions bottom">&raquo; <%= link_to 'zurück zum Dashboard', projects_path, :class => "back-to-dashboard" %></p>
<p> </p>

<% content_for :headertitle do %>
   <%= @project.title %>
<% end %>

<% content_for :contentmenu do %>
   <li><%= link_to "Übersicht", project_path%></li>
   <li><%= link_to "Aufgaben", todos_project_path, :class => "active" %></li>
   <li><%= link_to "Zeit", time_project_path %></li>
<% end %>

<% content_for :sidebar do %>
    <%= link_to 'Neue Aufgabe hinzufügen', new_project_to_do_path(@project), :class => 'todo-add', :title => 'Neue Aufgabe hinzufügen' %>
  </aside>
  <%= render 'projectlist' %>
<% end %>

app/views/projects/work.html.erb
<p class="actions">&raquo; <%= link_to 'neues Projekt erstellen', new_project_path, :class => "create-new" %></p>

<ul class="overview overview-work">
<% @projects.each do |project| %>
  <li id="project-<%= project.id %>">
    <h4>
	  <%= link_to project.title, project %>
	  <div class="project-actions">
	    <%= link_to 'Show', project %>
        <%= link_to 'Edit', edit_project_path(project) %>
        <%= link_to 'Destroy', project, confirm: 'Are you sure?', method: :delete %>
      </div>
	</h4>
	<p><%= project.description %></p>
    
    <p class="time">Zeiterfassung gesamt: <strong><%= project.to_dos.sum(:time) %> Stunden</strong></p>	
  </li>
<% end %>
</ul>

<% content_for :contentmenu do %>
   <li><%= link_to "Dashboard", projects_path %></li>
   <li><%= link_to "Arbeit", work_projects_path, :class => "active" %></li>
   <li><%= link_to "Studium", study_projects_path %></li>
<% end %>

app/views/to_dos/done.html.erb
<!-- Liste aller erledigten ToDos -->

app/views/to_dos/edit.html.erb
<h2 class="site-title">Aufgabe bearbeiten</h2>
<h4 class="site-subtitle"><%= @project.title %></h4>

<%= render 'form' %>


<% content_for :headertitle do %>
   <%= @project.title %>
<% end %>

<% content_for :contentmenu do %>
   <li><%= link_to "Übersicht", project_path(@project) %></li>
   <li><%= link_to "Aufgaben", todos_project_path(@project) %></li>
   <li><%= link_to "Zeit", time_project_path(@project) %></li>
<% end %>

app/views/to_dos/index.html.erb
<h1>Listing to_dos</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Kurzbeschreibung</th>
    <th>Details</th>
    <th>Deadline</th>
    <th>Zeiterfassung</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @to_dos.each do |to_do| %>
  <tr>
    <td><%= to_do.title %></td>
    <td><%= to_do.short_description %></td>
    <td><%= to_do.details %></td>
    <td><%= to_do.deadline %></td>
    <td><%= to_do.time %></td>
    <td><%= link_to 'Show', to_do %></td>
    <td><%= link_to 'Edit', edit_to_do_path(to_do) %></td>
    <td><%= link_to 'Destroy', to_do_path(@to_do), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Back to Project', projects_path %>

app/views/to_dos/new.html.erb
<h2 class="site-title">Neue Aufgabe hinzufügen</h2>
<h4 class="site-subtitle"><%= @project.title %></h4>

<%= render 'form' %>


<% content_for :headertitle do %>
   <%= @project.title %>
<% end %>

<% content_for :contentmenu do %>
   <li><%= link_to "Übersicht", project_path(@project) %></li>
   <li><%= link_to "Aufgaben", todos_project_path(@project) %></li>
   <li><%= link_to "Zeit", time_project_path(@project) %></li>
<% end %>

app/views/to_dos/show.html.erb
<p>
  <b>title:</b>
  <%= @to_do.title %>
</p>

<p>
  <b>Kurzbeschreibung:</b>
  <%= @to_do.short_description %>
</p>

<p>
  <b>Details:</b>
  <%= sanitize @to_do.details, :tags => %w(p br a strong em code) %>
</p>

<p>
  <b>Deadline:</b>
  <%= @to_do.deadline.to_formatted_s(:date_format) %>
</p>

<p>
  <b>Zeiterfassung:</b>
  <%= @to_do.time %>
</p>
<p>
  <b>Priorität:</b> <%=@to_do.priority %>
</p>
<p>
  <b>Erledigt:</b> <%=@to_do.done %>
</p>

<%= link_to 'Edit', edit_project_to_do_path(@project) %> |
<%= link_to 'Back', todos_project_path(@project) %> |
<%= link_to 'Destroy', :to_do, confirm: 'Are you sure?', method: :delete %> 


<% content_for :headertitle do %>
   <%= @project.title %>
<% end %>

<% content_for :contentmenu do %>
   <li><%= link_to "Übersicht", project_path(@project) %></li>
   <li><%= link_to "Aufgaben", todos_project_path(@project) %></li>
   <li><%= link_to "Zeit", time_project_path(@project) %></li>
<% end %>

<% content_for :sidebar do %>
	<%= link_to 'Aufgabe löschen', :to_do, confirm: 'Bist du sicher, dass du diese Aufgabe löschen möchtest?', method: :delete, :class => 'todo-delete', :title => 'Aufgabe löschen' %>
    <%= link_to 'Aufgabe bearbeiten', edit_project_to_do_path(@project), :class => 'todo-edit', :title => 'Aufgabe bearbeiten' %>
  </aside>
  <%= render 'todolist' %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.first_name %> <%= @user.last_name %></h1>
<p><%= @user.user_name %><br />
<%= @user.email %></p>

<%= gravatar_for @user, :size => 200 %>

<p>Du hast momentan <%= @user.projects.work.count %> Projekte und <%= @user.projects.study.count %> Lehrveranstaltungen.</p>


<% content_for :headertitle do %>
   <%= @user.user_name %>
<% end %>

<% content_for :contentmenu do %>
   <li><%= link_to 'Dashboard', projects_path %></li>
   <li><%= link_to 'Arbeit', work_projects_path %></li>
   <li><%= link_to 'Studium', study_projects_path %></li>
<% end %>

<% content_for :sidebar do %>
    <%= link_to 'Profil bearbeiten', edit_user_path(@user) %>
    <%= link_to 'Projekt/LVA hinzufügen', new_project_path(@project) %>
  </aside>
  <%= render 'projects/projectlist' %>
<% end %>